# Generated by Django 4.2.3 on 2023-07-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eron_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='subject',
        ),
    ]
