# Generated by Django 4.2.3 on 2023-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eron_app', '0002_remove_contactmodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=264, unique=True)),
                ('Emailaddress', models.EmailField(max_length=265, unique=True)),
                ('service', models.CharField(choices=[('Web design', 'WEB DESIGN'), ('Project management', 'PROJECT MANAGEMENT'), ('It training', 'IT TRAINING'), ('Remote support', 'REMOTE SUPPORT'), ('Cloud computing', 'CLOUD COMPUTING'), ('Programming and development', 'PROGRAMMING AND DEVELOPMENT')], default='Web design', max_length=50)),
            ],
        ),
    ]
