# Generated by Django 4.2.3 on 2023-07-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eron_app', '0003_servicemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='Emailaddress',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='servicemodel',
            old_name='FullName',
            new_name='Fullname',
        ),
    ]
